### ISSUE TITLE
Unable to Get ov7251 from Arducam Working with libcamera

### ISSUE THREAD

**Issue by szym1998** [6by9/libcamera-old#1]
Hi,

I've been trying to follow the fixes provided in [this Raspberry Pi forum thread](https://forums.raspberrypi.com/viewtopic.php?t=359478) to get the Arducam ov7251 sensor working, but I've had no success so far.

I attempted to compile your ov7251 branch following the suggested steps, and while the compilation completed without obvious errors, I'm unsure if the build is correct or being used properly. Specifically, running libcamera-hello --version still shows the currently installed system version of libcamera, rather than the new build I compiled.

Additionally, I reached out to Arducam for support but have not yet received a response.

Are there any chances of getting the ov7251 sensor to work with a mainstream version of libcamera in the future? Any guidance on properly compiling and using the custom libcamera build with the ov7251 sensor would be greatly appreciated.

Thank you!

**Comment by 6by9** [comment]
If you're building your own version of libcamera, then you're best off using `apt purge libcamera...` (with whichever extension is current) to get rid of the system versions first. System versions tend to go in /usr/lib whilst self-built go in /usr/local/lib, and then search order matters.

There's very little extra work to do for ov7251 as it has a mainline driver. Tuning requirements are minimal as it's a mono sensor, and copying ov9281 is probably sufficient. I may see if I can find the couple of minutes to verify it.

However this is my fork of libcamera only used for creating PRs and quick hacks, so I'll close this issue here. If you haven't seen anything within a couple of weeks, open a thread on the forums, or an issue on https://github.com/raspberrypi/libcamera for comment by those who are actively working on libcamera.
